// AUTHORIZATION/AUTHENTICATION/ACCOUNTS
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const EDIT_USER_ACCOUNT_SUCCESS = "EDIT_USER_ACCOUNT_SUCCESS";
export const EDIT_USER_ACCOUNT_FAIL = "EDIT_USER_ACCOUNT_FAIL";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_FAIL = "CHANGE_USER_PASSWORD_FAIL";
export const EDIT_USER_AVATAR_SUCCESS = "EDIT_USER_AVATAR_SUCCESS";
export const EDIT_USER_AVATAR_FAIL = "EDIT_USER_AVATAR_FAIL";
export const REMOVE_USER_AVATAR_SUCCESS = "REMOVE_USER_AVATAR_SUCCESS";
export const REMOVE_USER_AVATAR_FAIL = "REMOVE_USER_AVATAR_FAIL";
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// ERROR HANDLING
export const FETCH_ERRORS = "FETCH_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// FRIEND ACTIONS
export const GET_ALL_FRIENDS_SUCCESS = "GET_ALL_FRIENDS_SUCCESS";
export const GET_ALL_FRIENDS_FAIL = "GET_ALL_FRIENDS_FAIL";
export const GET_FRIEND_SUCCESS = "GET_FRIEND_SUCCESS";
export const GET_FRIEND_FAIL = "GET_FRIEND_FAIL";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL";
// OTHER USER ACTIONS
export const REPORT_USER = "REPORT_USER";
export const BLOCK_USER = "BLOCK_USER";
// MESSAGES ACTIONS
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
// potential action creators below
export const FETCH_ROOMS = "FETCH_ROOMS";
export const FETCH_ROOM = "FETCH_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
// SAME THING AS ROOMS BUT CHANNELS

// modal status actions
export const MODAL_STATUS_RESET = "MODAL_STATUS_RESET";

// loader status options
export const ACTION_SHOW_LOADER = "ACTION_SHOW_LOADER";
// export const LOGIN_FORM_SHOW_LOADER = "LOGIN_FORM_SHOW_LOADER";
// export const LOGIN_FORM_HIDE_LOADER = "LOGIN_FORM_HIDE_LOADER";
// export const EDIT_ACCOUNT_SHOW_LOADER = "EDIT_ACCOUNT_SHOW_LOADER";
// export const EDIT_ACCOUNT_HIDE_LOADER = "EDIT_ACCOUNT_HIDE_LOADER";
// export const CHANGE_PASSWORD_SHOW_LOADER = "CHANGE_PASSWORD_SHOW_LOADER";
// export const CHANGE_PASSWORD_HIDE_LOADER = "CHANGE_PASSWORD_HIDE_LOADER";

// export const  ="";
