// AUTHORIZATION/AUTHENTICATION/ACCOUNTS
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const EDIT_USER_ACCOUNT = "EDIT_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// ERROR HANDLING
export const FETCH_ERRORS = "FETCH_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// OTHER USER ACTIONS
export const ADD_FRIEND_USER = "ADD_FRIEND_USER";
export const BLOCK_USER = "BLOCK_USER";
// MESSAGES ACTIONS
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
// potential action creators below
export const FETCH_ROOMS = "FETCH_ROOMS";
export const FETCH_ROOM = "FETCH_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
// SAME THING AS ROOMS BUT CHANNELS

// export const  ="";
